/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JOptionPane;


/**
 *
 * @author kaustubh
 */
public class admit extends javax.swing.JFrame {

    /**
     * Creates new form admit
     */
    public admit() {
        super("ADMIT CARD");
        initComponents();
        insert_show_data();
        insert_show_data3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setSize(new java.awt.Dimension(800, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(400);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(700);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 497, 302));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 112, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 114, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRN", "Name", "Total Credits", "Seat No."
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 48));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Total"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 80, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Study\\DMS\\Lab\\Mini Project\\MIT_Logo_-_Copy-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, 59));

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Study\\DMS\\Lab\\Mini Project\\mitaoe.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1000, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new login().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
             public void insert_show_data3() {
        try{           
       Class.forName("com.mysql.cj.jdbc.Driver");  
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
    
        String query2 = "SELECT registered.C_ID,course.C_Name,course.C_Credits FROM registered,course WHERE registered.S_ID = "+ login.user+" and "+"course.C_ID=registered.C_ID";
        java.sql.PreparedStatement pst = conn.prepareStatement(query2);
	 java.sql.ResultSet
                 rs = pst.executeQuery(query2);
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
         model.setRowCount(0);
	while(rs.next()) {
	Object o[]={rs.getInt("C_ID"),rs.getString("C_Name"),rs.getInt("C_Credits")};
        model.addRow(o);
    }
           }
   catch(Exception e){
       e.printStackTrace();
   }  
    }
             
               public void insert_show_data() {
        try{           
       Class.forName("com.mysql.cj.jdbc.Driver");  
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
    
        String query2 = "SELECT * FROM student WHERE S_ID = "+ login.user;
        java.sql.PreparedStatement pst = conn.prepareStatement(query2);
	 java.sql.ResultSet
                 rs = pst.executeQuery(query2);
         DefaultTableModel model = (DefaultTableModel)jTable2.getModel(); 
         model.setRowCount(0);
	while(rs.next()) {
	Object o[]={rs.getInt("S_ID"),rs.getString("S_Name"),rs.getInt("S_Cred"),rs.getInt("S_Seatno")};
        model.addRow(o);
         }
        
         String query3 = "SELECT SUM(C_Credits) FROM registered WHERE S_ID = "+ login.user;
        java.sql.PreparedStatement pst2 = conn.prepareStatement(query3);
	 java.sql.ResultSet
                 rs2 = pst2.executeQuery(query3);
         DefaultTableModel model2 = (DefaultTableModel)jTable3.getModel(); 
         model2.setRowCount(0);
	while(rs2.next()) {
	Object o[]={rs2.getInt("SUM(C_Credits)")};
        model2.addRow(o);
         }
 
           }
   catch(Exception e){
       e.printStackTrace();
   }  
    }
               
               
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
