/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;
import java.sql.DriverManager;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author kaustubh
 */
public class home extends javax.swing.JFrame {
    public static int cred;
    public static int sum;
    public static int cid;
    /**
     * Creates new form home
     */
    public home() {
         super("HOME");
        initComponents();
        insert_show_data();
        insert_show_data2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1280));
        setSize(new java.awt.Dimension(1672, 764));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Courses");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 160, -1));

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jTable2.setShowGrid(false);
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(90);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 580, 270));

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setShowGrid(false);
        jScrollPane5.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable3.getColumnModel().getColumn(2).setMaxWidth(90);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 250, 490, 270));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 145, 36));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 123, 36));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 133, 47));

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Print Admit Card");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, 45));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRN", "Name", "Credits", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setMaxWidth(300);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 640, 48));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 30, 137, 45));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registration of Course");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 426, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   Registered Courses");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 426, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Study\\DMS\\Lab\\Mini Project\\library-books1.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 1920, 1280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  try{
          Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");

            cid = Integer.parseInt(jTextField1.getText());
            java.sql.PreparedStatement pst1 = conn.prepareStatement("select C_Credits from course where C_ID="+cid);
            java.sql.ResultSet rs1 = pst1.executeQuery();
            rs1.next();
             cred = rs1.getInt("C_Credits");
            if(validate_credit())
            {
        if(validate_course())
        {

            String query1 = "INSERT INTO registered VALUES("+login.user+","+cid+","+cred+")";
            java.sql.PreparedStatement pst = conn.prepareStatement(query1);
            int rs = pst.executeUpdate(query1);
            JOptionPane.showMessageDialog(null, "You have registered for the course ID "+cid);
            insert_show_data3(); 
        }
        else
        {
        JOptionPane.showMessageDialog(null, "You have already registered for the course.");
        }
            }
            else
            {
               JOptionPane.showMessageDialog(null, "You cannot register for the course.(Credits are greater than alloted credits)");
            }

        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

     private boolean validate_credit() {
  try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
       java.sql.PreparedStatement pst = conn.prepareStatement("select SUM(C_Credits) from registered where S_ID= "+login.user);
       java.sql.ResultSet rs1 = pst.executeQuery();
       java.sql.PreparedStatement pst2 = conn.prepareStatement("select S_Cred from student where S_ID= "+login.user);
       java.sql.ResultSet rs2 = pst2.executeQuery();
     /*  int sum=0;
       int c1;
               while ((rs1.next())) {
             c1 = rs1.getInt(1);
            sum = sum + c1;
        }*/
        rs1.next();
       int c1=rs1.getInt("SUM(C_Credits)");
               rs2.next();
       int c2=rs2.getInt("S_Cred");
       int c=c1+cred;
       if(c<=c2)
           return true;
       else
           return false;
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }       
}
     
      private boolean validate_course() {
  try{
       Class.forName("com.mysql.cj.jdbc.Driver");
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
       java.sql.PreparedStatement pst = conn.prepareStatement("select count(C_ID) from registered where S_ID= "+login.user+" and C_ID= "+cid);
       java.sql.ResultSet rs1 = pst.executeQuery();
       rs1.next();
       int c2=rs1.getInt("count(C_ID)");
       if(c2==0)
           return true;
       else
           return false;
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }       
}
     
     
     
     
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new admit().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       new login().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
   public void insert_show_data() {
        try{           
       Class.forName("com.mysql.cj.jdbc.Driver");  
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
    
        String query2 = "SELECT student.S_ID,student.S_Name,student.S_Cred,department.Dept_Name FROM student,department WHERE S_ID = "+ login.user+" AND student.Dep_ID=department.Dept_ID ";
        java.sql.PreparedStatement pst = conn.prepareStatement(query2);
	 java.sql.ResultSet
                 rs = pst.executeQuery(query2);
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
         model.setRowCount(0);
	while(rs.next()) {
	Object o[]={rs.getInt("S_ID"),rs.getString("S_Name"),rs.getInt("S_Cred"),rs.getString("Dept_Name")};
        model.addRow(o);
    }
           }
   catch(Exception e){
       e.printStackTrace();
   }  
    }
          public void insert_show_data2() {
        try{           
       Class.forName("com.mysql.cj.jdbc.Driver");  
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
    
        String query2 = "SELECT * FROM course WHERE D_ID = (SELECT Dep_ID from student where S_ID= "+login.user+")";
        java.sql.PreparedStatement pst = conn.prepareStatement(query2);
	 java.sql.ResultSet
                 rs = pst.executeQuery(query2);
         DefaultTableModel model = (DefaultTableModel)jTable2.getModel(); 
         model.setRowCount(0);
	while(rs.next()) {
	Object o[]={rs.getInt("C_ID"),rs.getString("C_Name"),rs.getInt("C_Credits")};
        model.addRow(o);
    }
           }
   catch(Exception e){
       e.printStackTrace();
   }  
          }
         
    public void insert_show_data3() {
        try{           
       Class.forName("com.mysql.cj.jdbc.Driver");  
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_project?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
       
       String query = "SELECT registered.C_ID,course.C_Name,course.C_Credits FROM registered,course WHERE registered.S_ID = "+ login.user+" and "+"course.C_ID=registered.C_ID";
        java.sql.PreparedStatement pst = conn.prepareStatement(query);
	 java.sql.ResultSet
                 rs = pst.executeQuery(query);
         DefaultTableModel model = (DefaultTableModel)jTable3.getModel(); 
         model.setRowCount(0);
	while(rs.next()) {
	Object o[]={rs.getInt("C_ID"),rs.getString("C_Name"),rs.getInt("C_Credits")};
        model.addRow(o);
    
           }
             }
   catch(Exception e){
       e.printStackTrace();
   }  
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
